global:
  scrape_interval: 5s
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: aula
  static_configs:
  - targets:
    - 192.168.0.14:3030
- job_name: servidor
  static_configs:
  - targets:
    - 192.168.0.14:9182
    
    
    
global:
  scrape_interval: 5s
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
    
- job_name: sipladgateway
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /actuator/prometheus
  scheme: http
  static_configs:
  - targets:
    - serivcegateway:8900
    
- job_name: sipladserviceautenticacao
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /actuator/prometheus
  scheme: http
  static_configs:
  - targets:
    - serviceautenticacao:9100
 
 - job_name: sipladserviceapoio
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /actuator/prometheus
  scheme: http
  static_configs:
  - targets:
    - serviceapoio:9300
 
- job_name: sipladserviceteste
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /actuator/prometheus
  scheme: http
  static_configs:
  - targets:
    - serviceteste:9300