spring:
  profiles:
    active:
    - default
server:
  port: ${PORT:9300}
  compression:
    enabled: true
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 30
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
        
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
      