version: '3.7'
volumes:
  grafana-storage:
  prometheus:
services:
  prometheus:
    image: prom/prometheus
    command: ["--config.file=/prometheus-data/prometheus.yml"]
    volumes:
      - ./prometheus-data:/prometheus-data
      - prometheus:/prometheus
    ports:
      - 9090:9090
    networks: 
      - sipladnetwork
      
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks: 
      - sipladnetwork
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - sipladnetwork

networks:
  sipladnetwork:
    external: true
    name: sipladnetwork


