version: '3.3'

services:

  servicediscovery:
    image: siplad/service-discovery:1.0
    restart: always
    ports:
       - "8800:8800"
  
  servicegateway:
    image: siplad/service-gateway:1.0
    restart: always
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicediscovery:8800/eureka/
    ports:
    - "8900:8900"
    depends_on:
      - servicediscovery
  
  fooservice:
    image: foo/foo-service:1.0
    restart: always
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicediscovery:8800/eureka/
    ports:
    - "9000:9000"
    depends_on:
      - servicediscovery
      - servicegateway
    