spring:
  profiles:
    active:
    - default

server:
  port: ${PORT:8900}
  compression:
    enabled: true

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 30
    prefer-ip-address: true
    
zuul:
  prefix: /api #prefixa a URI com /api
  ignored-services:
  - '*'
  routes:
    fooservice: #fooservice
      path: /v1/fooservice/** # mapeia para o /v1/fooservice
      service-id: fooservice  # localizado pelo service discovery pelo service-id fooservice
      strip-prefix: false
      
management:
  endpoints:
    web:
      exposure:
        include:
        - routes
        - info
        - env
        - refresh