spring:
  profiles:
    active:
    - default
  zipkin:
    base-url: http://192.168.126.5:9411
    
server:
  port: ${PORT:8800}
  compression:
    enabled: true
    
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
      
# Configuracao do arquivo de log  - Sera utilizado quando utilizar o docker. Sera mapeado o volume do conteiner para o host para acessar os logs da aplicacao
logging:
  file: ${spring.application.name}.log