version: '3.7'
services:

  servicediscovery:
    image: siplad/siplad-service-discovery:1.0
    environment:
    - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
    ports:
      - "8800:8800"
    networks:
      - sipladnetwork-overlay
  
  servicegateway:
    image: siplad/siplad-gateway:1.0
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicediscovery:8800/eureka/
    - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
    ports:
      - "8900:8900"
    networks:
      - sipladnetwork-overlay

  serviceapoio:
    image: siplad/siplad-service-apoio:1.0
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicediscovery:8800/eureka/
    - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
    ports:
    - "9300:9300"
    networks:
      - sipladnetwork-overlay

  serviceautenticacao:
    image: siplad/siplad-service-autenticacao:1.0
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicediscovery:8800/eureka/
    - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
    ports:
    - "9100:9100"
    networks:
      - sipladnetwork-overlay
      
  servicesipladteste:
    image: siplad/siplad-service-teste:1.0
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicediscovery:8800/eureka/
    - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
    ports:
    - "9600:9600"
    networks:
      - sipladnetwork-overlay

networks:
  sipladnetwork-overlay:
    external:
      name: sipladnetwork-overlay
