version: '3'

services:

  servicediscovery:
    image: siplad/servicediscovery-1.0
    ports:
       - "8800:8800"
  
  servicegateway:
    image: siplad/service-gateway-1.0
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicediscovery:8800/eureka/
    ports:
    - "8900:8900"
    depends_on:
      - servicediscovery    
    
    