version: '3'

services:

  servicegateway:
    image: siplad/service-gateway:1.0
    networks:
      - sipladnetwork-overlay
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicediscovery:8800/eureka/
    - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
    ports:
    - "8900:8900"
    
networks:
  sipladnetwork-overlay:
    external:
      name: sipladnetwork-overlay
