version: '3'

services:

  servicediscovery:
    image: siplad/service-discovery:1.0
    networks:
      sipladnetwork-overlay:
        aliases:
        - eureka
    environment:
    - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
    ports:
       - "8800:8800"

networks:
  sipladnetwork-overlay:
    external:
      name: sipladnetwork-overlay
