spring:
  profiles:
    active:
    - default
server:
  port: ${PORT:9000}
  compression:
    enabled: true
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 30
    prefer-ip-address: true